#!/usr/bin/env python3
"""Adopt external preprocessing outputs into a Clutt3R-Seg sequence.

The original experiment pipeline runs MVSAnywhere and Grounded-SAM before
Clutt3R-Seg. This helper preserves measured depth as a side input, then installs
the generated MVS depth and instance masks where the release pipeline expects
them.
"""

from __future__ import annotations

import argparse
import json
import re
import shutil
from datetime import datetime, timezone
from pathlib import Path
from typing import Iterable


DEPTH_EXTENSIONS = (".png", ".npy")


def same_path(lhs: Path, rhs: Path) -> bool:
    try:
        return lhs.resolve() == rhs.resolve()
    except FileNotFoundError:
        return lhs.absolute() == rhs.absolute()


def remove_path(path: Path) -> None:
    if path.is_symlink() or path.is_file():
        path.unlink()
    elif path.exists():
        shutil.rmtree(path)


def copy_tree(src: Path, dst: Path, *, overwrite: bool) -> None:
    if same_path(src, dst):
        return

    if dst.exists():
        if not overwrite:
            raise FileExistsError(f"{dst} already exists. Pass --overwrite to replace it.")
        remove_path(dst)

    shutil.copytree(src, dst)


def has_depth_files(path: Path) -> bool:
    return any(any(path.glob("depth_*" + ext)) for ext in DEPTH_EXTENSIONS)


def has_instance_masks(path: Path) -> bool:
    return any(path.glob("mask_*.png"))


def find_dir_with_files(root: Path, dirname: str, predicate) -> Path:
    if not root.exists():
        raise FileNotFoundError(root)

    if root.is_dir() and predicate(root):
        return root

    direct = root / dirname
    if direct.exists() and predicate(direct):
        return direct

    for candidate in root.rglob(dirname):
        if candidate.is_dir() and predicate(candidate):
            return candidate

    raise FileNotFoundError(f"Could not find a usable {dirname}/ directory under {root}.")


def require_preprocess_output(path: Path, *, label: str, expected: str) -> None:
    if path.exists():
        return

    raise FileNotFoundError(
        f"Missing {label} output directory: {path}\n"
        "This script only adopts outputs that were already generated by external preprocessors; "
        "it does not run MVSAnywhere or Grounded-SAM.\n"
        f"Expected {label} output to contain: {expected}"
    )


def read_frames(data_dir: Path) -> list[dict]:
    transforms_path = data_dir / "transforms.json"
    if not transforms_path.exists():
        raise FileNotFoundError(f"Missing {transforms_path}")

    meta = json.loads(transforms_path.read_text())
    frames = meta.get("frames", [])
    if not frames:
        raise ValueError(f"{transforms_path} does not contain any frames.")
    return frames


def expected_depth_paths(data_dir: Path, frames: Iterable[dict]) -> list[Path]:
    paths = []
    for frame in frames:
        rel_path = Path(frame["depth_file_path"]).with_suffix(".png")
        paths.append(data_dir / rel_path)
    return paths


def preserve_measured_depth(data_dir: Path, *, mvs_depth_src: Path | None) -> str:
    depth_dir = data_dir / "depth"
    measured_dir = data_dir / "measured_depth"

    if not depth_dir.exists():
        return "No existing data/depth directory to preserve."

    if mvs_depth_src is not None and same_path(depth_dir, mvs_depth_src):
        return "data/depth already points to the MVS depth source; it was not moved."

    if measured_dir.exists():
        return "data/measured_depth already exists; it was left unchanged."

    shutil.move(str(depth_dir), str(measured_dir))
    return f"Moved {depth_dir} to {measured_dir}."


def install_mvs_depth(data_dir: Path, mvs_output: Path, *, overwrite: bool) -> list[str]:
    actions = []
    depth_src = find_dir_with_files(mvs_output, "depth", has_depth_files)
    stored_depth = data_dir / "mvsanywhere_depth"
    active_depth = data_dir / "depth"

    copy_tree(depth_src, stored_depth, overwrite=overwrite)
    actions.append(f"Stored MVSAnywhere depth in {stored_depth}.")

    copy_tree(stored_depth, active_depth, overwrite=overwrite)
    actions.append(f"Installed MVSAnywhere depth as active depth in {active_depth}.")
    return actions


def install_grounded_sam(data_dir: Path, sam_output: Path, *, overwrite: bool) -> list[str]:
    actions = []
    instance_src = find_dir_with_files(sam_output, "instance_masks", has_instance_masks)
    copy_tree(instance_src, data_dir / "instance_masks", overwrite=overwrite)
    actions.append(f"Installed Grounded-SAM instance masks from {instance_src}.")

    for optional_name in ("masks", "overlay"):
        optional_src = sam_output / optional_name
        if optional_src.exists():
            copy_tree(optional_src, data_dir / optional_name, overwrite=overwrite)
            actions.append(f"Copied optional Grounded-SAM {optional_name}/ outputs.")

    return actions


def summarize_validation(data_dir: Path, frames: list[dict]) -> list[str]:
    messages = []

    missing_depth = [path for path in expected_depth_paths(data_dir, frames) if not path.exists()]
    if missing_depth:
        preview = ", ".join(str(path) for path in missing_depth[:5])
        suffix = "" if len(missing_depth) <= 5 else f", ... ({len(missing_depth)} total)"
        messages.append(f"Missing active depth files: {preview}{suffix}")
    else:
        messages.append(f"Active depth is ready for {len(frames)} frames.")

    instance_dir = data_dir / "instance_masks"
    if not instance_dir.exists():
        messages.append("Missing data/instance_masks.")
        return messages

    mask_frames = set()
    pattern = re.compile(r"mask_(\d{6})_\d+\.png$")
    for mask_path in instance_dir.glob("mask_*.png"):
        match = pattern.match(mask_path.name)
        if match:
            mask_frames.add(int(match.group(1)))

    if not mask_frames:
        messages.append("No per-frame instance masks were found.")
    else:
        messages.append(
            f"Instance masks are available for {len(mask_frames)} frame(s): "
            f"{min(mask_frames)}..{max(mask_frames)}."
        )

    return messages


def write_manifest(data_dir: Path, args: argparse.Namespace, actions: list[str], validation: list[str]) -> None:
    manifest = {
        "created_at": datetime.now(timezone.utc).isoformat(),
        "sequence_dir": str(args.sequence_dir.resolve()),
        "mvs_output": str(args.mvs_output.resolve()) if args.mvs_output else None,
        "sam_output": str(args.sam_output.resolve()) if args.sam_output else None,
        "actions": actions,
        "validation": validation,
    }
    (data_dir / "preprocess_manifest.json").write_text(json.dumps(manifest, indent=2) + "\n")


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(
        description="Preserve measured depth and adopt MVSAnywhere/Grounded-SAM outputs."
    )
    parser.add_argument("sequence_dir_pos", nargs="?", type=Path, help="Sequence directory, e.g. samples/sample_seq2")
    parser.add_argument("--sequence-dir", dest="sequence_dir_opt", type=Path, help="Sequence directory.")
    parser.add_argument("--mvs-output", type=Path, help="Directory containing MVSAnywhere depth/ output.")
    parser.add_argument("--sam-output", type=Path, help="Directory containing Grounded-SAM instance_masks/ output.")
    parser.add_argument(
        "--overwrite",
        action="store_true",
        help="Replace existing active/generated outputs such as data/depth or data/instance_masks.",
    )
    parser.add_argument(
        "--keep-active-depth",
        action="store_true",
        help="Do not move an existing data/depth directory to data/measured_depth before installing MVS depth.",
    )
    args = parser.parse_args()

    args.sequence_dir = args.sequence_dir_opt or args.sequence_dir_pos
    if args.sequence_dir is None:
        parser.error("A sequence directory is required.")
    return args


def main() -> None:
    args = parse_args()
    sequence_dir = args.sequence_dir
    data_dir = sequence_dir / "data"
    if not data_dir.exists():
        raise FileNotFoundError(f"Missing {data_dir}")

    frames = read_frames(data_dir)
    actions = []

    mvs_depth_src = None
    if args.mvs_output:
        require_preprocess_output(
            args.mvs_output,
            label="MVSAnywhere",
            expected="depth/depth_*.png",
        )
        mvs_depth_src = find_dir_with_files(args.mvs_output, "depth", has_depth_files)

    if not args.keep_active_depth:
        actions.append(preserve_measured_depth(data_dir, mvs_depth_src=mvs_depth_src))

    if args.mvs_output:
        actions.extend(install_mvs_depth(data_dir, args.mvs_output, overwrite=args.overwrite))

    if args.sam_output:
        require_preprocess_output(
            args.sam_output,
            label="Grounded-SAM",
            expected="instance_masks/mask_*.png",
        )
        actions.extend(install_grounded_sam(data_dir, args.sam_output, overwrite=args.overwrite))

    validation = summarize_validation(data_dir, frames)
    write_manifest(data_dir, args, actions, validation)

    return


if __name__ == "__main__":
    main()
